#if os(WASI)

public struct Event {
	/// Event type enum matching the Event.type DOM API
	public enum `Type`: String {
		case click = "click"
		case change = "change"
		case input = "input"
		case submit = "submit"
		case focus = "focus"
		case blur = "blur"
		case keydown = "keydown"
		case keyup = "keyup"
		case keypress = "keypress"
		case mousedown = "mousedown"
		case mouseup = "mouseup"
		case mouseover = "mouseover"
		case mouseout = "mouseout"
		case mouseenter = "mouseenter"
		case mouseleave = "mouseleave"
		case mousemove = "mousemove"
		case scroll = "scroll"
		case resize = "resize"
		case load = "load"
		case unload = "unload"
		case transitionend = "transitionend"
		case toggle = "toggle"
		case touchstart = "touchstart"
		case touchend = "touchend"
		case touchmove = "touchmove"
		case touchcancel = "touchcancel"

		public var staticString: StaticString {
			switch self {
				case .click: return "click"
				case .change: return "change"
				case .input: return "input"
				case .submit: return "submit"
				case .focus: return "focus"
				case .blur: return "blur"
				case .keydown: return "keydown"
				case .keyup: return "keyup"
				case .keypress: return "keypress"
				case .mousedown: return "mousedown"
				case .mouseup: return "mouseup"
				case .mouseover: return "mouseover"
				case .mouseout: return "mouseout"
				case .mouseenter: return "mouseenter"
				case .mouseleave: return "mouseleave"
				case .mousemove: return "mousemove"
				case .scroll: return "scroll"
				case .resize: return "resize"
				case .load: return "load"
				case .unload: return "unload"
				case .transitionend: return "transitionend"
				case .toggle: return "toggle"
				case .touchstart: return "touchstart"
				case .touchend: return "touchend"
				case .touchmove: return "touchmove"
				case .touchcancel: return "touchcancel"
			}
		}
	}

	// Static members for shorthand access
	public static let click: StaticString = "click"
	public static let change: StaticString = "change"
	public static let input: StaticString = "input"
	public static let submit: StaticString = "submit"
	public static let focus: StaticString = "focus"
	public static let blur: StaticString = "blur"
	public static let keydown: StaticString = "keydown"
	public static let keyup: StaticString = "keyup"
	public static let keypress: StaticString = "keypress"
	public static let mousedown: StaticString = "mousedown"
	public static let mouseup: StaticString = "mouseup"
	public static let mouseover: StaticString = "mouseover"
	public static let mouseout: StaticString = "mouseout"
	public static let mouseenter: StaticString = "mouseenter"
	public static let mouseleave: StaticString = "mouseleave"
	public static let mousemove: StaticString = "mousemove"
	public static let scroll: StaticString = "scroll"
	public static let resize: StaticString = "resize"
	public static let load: StaticString = "load"
	public static let unload: StaticString = "unload"
	public static let transitionend: StaticString = "transitionend"
	public static let toggle: StaticString = "toggle"
	public static let touchstart: StaticString = "touchstart"
	public static let touchend: StaticString = "touchend"
	public static let touchmove: StaticString = "touchmove"
	public static let touchcancel: StaticString = "touchcancel"
}

#endif
